/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFaucet } from "./IFaucet";
export type { IIdentity } from "./IIdentity";
export type { INameService } from "./INameService";
export type { TokenBridge } from "./TokenBridge";
