/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blockRegistry from "./blockRegistry";
export type { blockRegistry };
import type * as bridge from "./bridge";
export type { bridge };
import type * as fuse from "./fuse";
export type { fuse };
import type * as messagePassingBridge from "./messagePassingBridge";
export type { messagePassingBridge };
import type * as test from "./test";
export type { test };
