/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCallSol from "./MultiCall.sol";
export type { multiCallSol };
import type * as testTokenSol from "./TestToken.sol";
export type { testTokenSol };
import type * as votingMockSol from "./VotingMock.sol";
export type { votingMockSol };
export type { ConsensusMock } from "./ConsensusMock";
export type { ControllerMock } from "./ControllerMock";
export type { LayerZeroEndpointMock } from "./LayerZeroEndpointMock";
export type { MockGoodDollar } from "./MockGoodDollar";
export type { NameServiceMock } from "./NameServiceMock";
export type { TestRLPParser } from "./TestRLPParser";
export type { TokenBridgeTest } from "./TokenBridgeTest";
export type { VerifierTest } from "./VerifierTest";
