/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingMockSol from "./VotingMock.sol";
export type { votingMockSol };
export type { ConsensusMock } from "./ConsensusMock";
export type { TestToken } from "./TestToken";
export type { VerifierTest } from "./VerifierTest";
