/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenBridgeSol from "./TokenBridge.sol";
export type { tokenBridgeSol };
export type { BridgeCore } from "./BridgeCore";
export type { BridgeMixedConsensus } from "./BridgeMixedConsensus";
