/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBlockHeaderRegistry } from "./IBlockHeaderRegistry";
export type { VotingMock } from "./VotingMock";
