/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace BlockHeaderRegistry {
  export type SignatureStruct = {
    r: PromiseOrValue<BytesLike>;
    vs: PromiseOrValue<BytesLike>;
  };

  export type SignatureStructOutput = [string, string] & {
    r: string;
    vs: string;
  };

  export type BlockStruct = {
    rlpHeader: PromiseOrValue<BytesLike>;
    signature: BlockHeaderRegistry.SignatureStruct;
    chainId: PromiseOrValue<BigNumberish>;
    blockHash: PromiseOrValue<BytesLike>;
    cycleEnd: PromiseOrValue<BigNumberish>;
    validators: PromiseOrValue<string>[];
  };

  export type BlockStructOutput = [
    string,
    BlockHeaderRegistry.SignatureStructOutput,
    BigNumber,
    string,
    BigNumber,
    string[]
  ] & {
    rlpHeader: string;
    signature: BlockHeaderRegistry.SignatureStructOutput;
    chainId: BigNumber;
    blockHash: string;
    cycleEnd: BigNumber;
    validators: string[];
  };

  export type BlockchainStruct = {
    rpc: PromiseOrValue<string>;
    chainId: PromiseOrValue<BigNumberish>;
  };

  export type BlockchainStructOutput = [string, BigNumber] & {
    rpc: string;
    chainId: BigNumber;
  };

  export type SignedBlockStruct = {
    signatures: PromiseOrValue<BytesLike>[];
    cycleEnd: PromiseOrValue<BigNumberish>;
    validators: PromiseOrValue<string>[];
    blockHash: PromiseOrValue<BytesLike>;
  };

  export type SignedBlockStructOutput = [
    string[],
    BigNumber,
    string[],
    string
  ] & {
    signatures: string[];
    cycleEnd: BigNumber;
    validators: string[];
    blockHash: string;
  };
}

export interface BlockHeaderRegistryInterface extends utils.Interface {
  functions: {
    "addBlockchain(uint256,string)": FunctionFragment;
    "addSignedBlocks((bytes,(bytes32,bytes32),uint256,bytes32,uint256,address[])[])": FunctionFragment;
    "blockHashes(uint256,uint256,uint256)": FunctionFragment;
    "cachedValidators(address)": FunctionFragment;
    "consensus()": FunctionFragment;
    "enabledBlockchains(uint256)": FunctionFragment;
    "getBlockHashByPayloadHash(bytes32)": FunctionFragment;
    "getRPCs()": FunctionFragment;
    "getSignedBlock(uint256,uint256)": FunctionFragment;
    "hasValidatorSigned(bytes32,address)": FunctionFragment;
    "initialize(address,address,bool)": FunctionFragment;
    "isEventsOnly()": FunctionFragment;
    "parseRLPBlockNumber(bytes)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "signedBlocks(bytes32)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "voting()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addBlockchain"
      | "addSignedBlocks"
      | "blockHashes"
      | "cachedValidators"
      | "consensus"
      | "enabledBlockchains"
      | "getBlockHashByPayloadHash"
      | "getRPCs"
      | "getSignedBlock"
      | "hasValidatorSigned"
      | "initialize"
      | "isEventsOnly"
      | "parseRLPBlockNumber"
      | "proxiableUUID"
      | "signedBlocks"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "voting"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addBlockchain",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addSignedBlocks",
    values: [BlockHeaderRegistry.BlockStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "blockHashes",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cachedValidators",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "consensus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "enabledBlockchains",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockHashByPayloadHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "getRPCs", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSignedBlock",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidatorSigned",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isEventsOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "parseRLPBlockNumber",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signedBlocks",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "voting", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addBlockchain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSignedBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consensus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enabledBlockchains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlockHashByPayloadHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRPCs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSignedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasValidatorSigned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEventsOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseRLPBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signedBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voting", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "BlockAdded(address,uint256,uint256,bytes32,address[],uint256,bytes)": EventFragment;
    "BlockchainAdded(uint256,string)": EventFragment;
    "BlockchainRemoved(uint256)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockchainAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockchainRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export interface AdminChangedEventObject {
  previousAdmin: string;
  newAdmin: string;
}
export type AdminChangedEvent = TypedEvent<
  [string, string],
  AdminChangedEventObject
>;

export type AdminChangedEventFilter = TypedEventFilter<AdminChangedEvent>;

export interface BeaconUpgradedEventObject {
  beacon: string;
}
export type BeaconUpgradedEvent = TypedEvent<
  [string],
  BeaconUpgradedEventObject
>;

export type BeaconUpgradedEventFilter = TypedEventFilter<BeaconUpgradedEvent>;

export interface BlockAddedEventObject {
  validator: string;
  chainId: BigNumber;
  blockNumber: BigNumber;
  payload: string;
  validators: string[];
  cycleEnd: BigNumber;
  signature: string;
}
export type BlockAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber, string, string[], BigNumber, string],
  BlockAddedEventObject
>;

export type BlockAddedEventFilter = TypedEventFilter<BlockAddedEvent>;

export interface BlockchainAddedEventObject {
  chainId: BigNumber;
  rpc: string;
}
export type BlockchainAddedEvent = TypedEvent<
  [BigNumber, string],
  BlockchainAddedEventObject
>;

export type BlockchainAddedEventFilter = TypedEventFilter<BlockchainAddedEvent>;

export interface BlockchainRemovedEventObject {
  chainId: BigNumber;
}
export type BlockchainRemovedEvent = TypedEvent<
  [BigNumber],
  BlockchainRemovedEventObject
>;

export type BlockchainRemovedEventFilter =
  TypedEventFilter<BlockchainRemovedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface UpgradedEventObject {
  implementation: string;
}
export type UpgradedEvent = TypedEvent<[string], UpgradedEventObject>;

export type UpgradedEventFilter = TypedEventFilter<UpgradedEvent>;

export interface BlockHeaderRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BlockHeaderRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addBlockchain(
      chainId: PromiseOrValue<BigNumberish>,
      rpc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSignedBlocks(
      blocks: BlockHeaderRegistry.BlockStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    blockHashes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    cachedValidators(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    consensus(overrides?: CallOverrides): Promise<[string]>;

    enabledBlockchains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rpc: string; chainId: BigNumber }>;

    getBlockHashByPayloadHash(
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { blockHash: string }>;

    getRPCs(
      overrides?: CallOverrides
    ): Promise<[BlockHeaderRegistry.BlockchainStructOutput[]]>;

    getSignedBlock(
      chainId: PromiseOrValue<BigNumberish>,
      number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BlockHeaderRegistry.SignedBlockStructOutput] & {
        signedBlock: BlockHeaderRegistry.SignedBlockStructOutput;
      }
    >;

    hasValidatorSigned(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      _voting: PromiseOrValue<string>,
      _consensus: PromiseOrValue<string>,
      _isEventsOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isEventsOnly(overrides?: CallOverrides): Promise<[boolean]>;

    parseRLPBlockNumber(
      rlpHeader: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { blockNumber: BigNumber }>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    signedBlocks(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { cycleEnd: BigNumber; blockHash: string }
    >;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voting(overrides?: CallOverrides): Promise<[string]>;
  };

  addBlockchain(
    chainId: PromiseOrValue<BigNumberish>,
    rpc: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSignedBlocks(
    blocks: BlockHeaderRegistry.BlockStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  blockHashes(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  cachedValidators(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  consensus(overrides?: CallOverrides): Promise<string>;

  enabledBlockchains(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { rpc: string; chainId: BigNumber }>;

  getBlockHashByPayloadHash(
    payloadHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getRPCs(
    overrides?: CallOverrides
  ): Promise<BlockHeaderRegistry.BlockchainStructOutput[]>;

  getSignedBlock(
    chainId: PromiseOrValue<BigNumberish>,
    number: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BlockHeaderRegistry.SignedBlockStructOutput>;

  hasValidatorSigned(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    _voting: PromiseOrValue<string>,
    _consensus: PromiseOrValue<string>,
    _isEventsOnly: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isEventsOnly(overrides?: CallOverrides): Promise<boolean>;

  parseRLPBlockNumber(
    rlpHeader: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  signedBlocks(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { cycleEnd: BigNumber; blockHash: string }>;

  upgradeTo(
    newImplementation: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: PromiseOrValue<string>,
    data: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voting(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addBlockchain(
      chainId: PromiseOrValue<BigNumberish>,
      rpc: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSignedBlocks(
      blocks: BlockHeaderRegistry.BlockStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    blockHashes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    cachedValidators(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consensus(overrides?: CallOverrides): Promise<string>;

    enabledBlockchains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rpc: string; chainId: BigNumber }>;

    getBlockHashByPayloadHash(
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getRPCs(
      overrides?: CallOverrides
    ): Promise<BlockHeaderRegistry.BlockchainStructOutput[]>;

    getSignedBlock(
      chainId: PromiseOrValue<BigNumberish>,
      number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BlockHeaderRegistry.SignedBlockStructOutput>;

    hasValidatorSigned(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(
      _voting: PromiseOrValue<string>,
      _consensus: PromiseOrValue<string>,
      _isEventsOnly: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    isEventsOnly(overrides?: CallOverrides): Promise<boolean>;

    parseRLPBlockNumber(
      rlpHeader: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    signedBlocks(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string] & { cycleEnd: BigNumber; blockHash: string }
    >;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    voting(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;
    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): AdminChangedEventFilter;

    "BeaconUpgraded(address)"(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;
    BeaconUpgraded(
      beacon?: PromiseOrValue<string> | null
    ): BeaconUpgradedEventFilter;

    "BlockAdded(address,uint256,uint256,bytes32,address[],uint256,bytes)"(
      validator?: PromiseOrValue<string> | null,
      chainId?: PromiseOrValue<BigNumberish> | null,
      blockNumber?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      validators?: null,
      cycleEnd?: null,
      signature?: null
    ): BlockAddedEventFilter;
    BlockAdded(
      validator?: PromiseOrValue<string> | null,
      chainId?: PromiseOrValue<BigNumberish> | null,
      blockNumber?: PromiseOrValue<BigNumberish> | null,
      payload?: null,
      validators?: null,
      cycleEnd?: null,
      signature?: null
    ): BlockAddedEventFilter;

    "BlockchainAdded(uint256,string)"(
      chainId?: null,
      rpc?: null
    ): BlockchainAddedEventFilter;
    BlockchainAdded(chainId?: null, rpc?: null): BlockchainAddedEventFilter;

    "BlockchainRemoved(uint256)"(chainId?: null): BlockchainRemovedEventFilter;
    BlockchainRemoved(chainId?: null): BlockchainRemovedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "Upgraded(address)"(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
    Upgraded(
      implementation?: PromiseOrValue<string> | null
    ): UpgradedEventFilter;
  };

  estimateGas: {
    addBlockchain(
      chainId: PromiseOrValue<BigNumberish>,
      rpc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSignedBlocks(
      blocks: BlockHeaderRegistry.BlockStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    blockHashes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cachedValidators(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    consensus(overrides?: CallOverrides): Promise<BigNumber>;

    enabledBlockchains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBlockHashByPayloadHash(
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRPCs(overrides?: CallOverrides): Promise<BigNumber>;

    getSignedBlock(
      chainId: PromiseOrValue<BigNumberish>,
      number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasValidatorSigned(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _voting: PromiseOrValue<string>,
      _consensus: PromiseOrValue<string>,
      _isEventsOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isEventsOnly(overrides?: CallOverrides): Promise<BigNumber>;

    parseRLPBlockNumber(
      rlpHeader: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    signedBlocks(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voting(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addBlockchain(
      chainId: PromiseOrValue<BigNumberish>,
      rpc: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSignedBlocks(
      blocks: BlockHeaderRegistry.BlockStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    blockHashes(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cachedValidators(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    consensus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enabledBlockchains(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBlockHashByPayloadHash(
      payloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRPCs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSignedBlock(
      chainId: PromiseOrValue<BigNumberish>,
      number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasValidatorSigned(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _voting: PromiseOrValue<string>,
      _consensus: PromiseOrValue<string>,
      _isEventsOnly: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isEventsOnly(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    parseRLPBlockNumber(
      rlpHeader: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    signedBlocks(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: PromiseOrValue<string>,
      data: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voting(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
